### ISSUE TITLE
Bug when running the Tests

### ISSUE THREAD

**Issue by lucasgr7** [lucasgr7/silverplate#15]
Having this problem when running the test, can someone help?

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.1\helpers\pycharm\utrunner.py", line 153, in <module>
    modules = [loadSource(a[0])]
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.1\helpers\pycharm\utrunner.py", line 65, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python35-32\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Projeto SP\silverplate\crawler\tests\test_crawler.py", line 3, in <module>
    from crawler.DataFinder import IngredientFinder
  File "C:\Projeto SP\silverplate\crawler\DataFinder.py", line 6, in <module>
    from crawler.models import DataIngredient, DataWayCooking
  File "C:\Projeto SP\silverplate\crawler\models.py", line 4, in <module>
    class DataIngredient(models.Model):
  File "C:\Projeto SP\silverplate\crawler\models.py", line 7, in DataIngredient
    ingredient = models.CharField(max_length=1000)
  File "C:\Projeto SP\env\lib\site-packages\django\db\models\fields__init__.py", line 1072, in **init**
    super(CharField, self).**init**(_args, *_kwargs)
  File "C:\Projeto SP\env\lib\site-packages\django\db\models\fields__init__.py", line 166, in **init**
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "C:\Projeto SP\env\lib\site-packages\django\conf__init__.py", line 55, in **getattr**
    self._setup(name)
  File "C:\Projeto SP\env\lib\site-packages\django\conf__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by mpsk2** [comment]
I did not have that bug, as well travis-ci did not have that bug.

**Comment by mpsk2** [comment]
`python manage.py test --settings=silverplate.settings.development`
Creating test database for alias 'default'...

## ......................

Ran 22 tests in 1.123s

OK
Destroying test database for alias 'default'...

Did you try running it from command prompt?

**Comment by chentr** [comment]
**But I can't even create tables by migration.**
after clone newest version,create database silverplate.
then run "python manage.py migrate" ,it crashed.
**Here is the error I get** :  

# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/core/management/**init**.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(_args, *_options)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in **init**
    self.build_graph()
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 293, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 286, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/venvs/djproject/lib/python3.5/site-packages/django/db/migrations/graph.py", line 126, in add_dependency
    parent
django.db.migrations.exceptions.NodeNotFoundError: Migration crawler.0004_auto_20160831_1049 dependencies reference nonexistent parent node ('crawler', '0003_auto_20160828_1355')

**Comment by mpsk2** [comment]
As you can read, there is not file 0003_auto_....
It is strange - I have that file in my fork. 
Anyway, the hotfix for that could be jut to create file crawler/migrations/0003_auto_20160828_1355.py
Still I have that in my fork, and i do not know why it does not appear in main repository.

you are missing that file: https://github.com/mpsk2/silverplate/blob/master/crawler/migrations/0003_auto_20160828_1355.py

**Comment by lucasgr7** [comment]
I will try to rebuild the migratiosn see what can i do.

Thanks

2016-09-10 12:16 GMT-03:00 Michał Piotr Stankiewicz <
notifications@github.com>:

**Comment by mpsk2** [comment]
I would suggest https://raw.githubusercontent.com/mpsk2/silverplate/master/crawler/migrations/0003_auto_20160828_1355.py

copy that file to directory crawler/migrations/

it should be done than

**Comment by mpsk2** [comment]
Did you solve the problem?

**Comment by lucasgr7** [comment]
not yet

2016-09-12 19:05 GMT-03:00 Michał Piotr Stankiewicz <
notifications@github.com>:

**Comment by lucasgr7** [comment]
i will try to reinstall django python and Pycharm on my computer, these
things don't seem to be working

2016-09-12 22:26 GMT-03:00 Lucas Garcia Ribeiro lucasgr7@gmail.com:

**Comment by mpsk2** [comment]
anyway, does anything changed in error report, if you have created a migration? can you list your files in crawler/migrations directory?

**Comment by lucasgr7** [comment]
I belive it's not a problem on migrations.
The message
"django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings."

Seems to be a problem on the django instance on my computer. I uinstalled yesterday, i left only python 2.7 there and didn't work.

Today i will try to re-install python 3.5 and django 1.10 to see if it fixes.

**Comment by mpsk2** [comment]
I do not recommend using Python2.7

I have fixed it and it works for me now!
Here is what I have done

```
git clone https://github.com/lucasgr7/silverplate.git
cd silverplate
virtualenv -p python3 venv 
source venv/bin/activate
pip install -r requirements.txt
cd silverplate/migrations/
wget https://raw.githubusercontent.com/mpsk2/silverplate/master/crawler/migrations/0003_auto_20160828_1355.py
cd ..
cd ..
python manage.py migrate
python init.py
```

And everthing works

**Comment by mpsk2** [comment]
I think that is a bug of github. I can see that file in git history: https://github.com/lucasgr7/silverplate/blob/f4a517297749b599a763cc5bc44db7545ea683cc/crawler/migrations/0003_auto_20160828_1355.py

but if you look at repo, there is no such file. On the othere hand, that file has only one commit, that adds it to the repository:
https://github.com/lucasgr7/silverplate/commits/f4a517297749b599a763cc5bc44db7545ea683cc/crawler/migrations/0003_auto_20160828_1355.py

What I recommend you to do is to do what I have done in above post and commit that file. I cannot commit it (it will be only rename, but that file does not exists here)

**Comment by mpsk2** [comment]
And I must admit, I have never run tests from PyCharm, I always do it by hand using `python manage.py test`. My tests run on Python3 both on windows and linux.

**Comment by lucasgr7** [comment]
i will re-create the migrattions then and commit it.
Shouldn't migrations not be commited on github? Each one compile their own migrations?

I will focus on trying to running the tests on my machine so i could go back to work and develop new features.

Thanks :+1:

**Comment by mpsk2** [comment]
I think it is some kind of bug on github. I have these migrations and i have pull requested them. It makes not sense if you do not have it.

**Comment by lucasgr7** [comment]
Fixed the problem
Re-installed the python 3.5 and didn't use the PyCharm.
I still wanna use PyCharm it helps to debug a lot.
And re-created the missing files of Migrations, and commited, time to re-start working on the project.
Thanks for te tips!
